"""empty message

Revision ID: 2dc2514d24e0
Revises: e3e87c690f9d
Create Date: 2017-11-06 10:26:38.483741

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dc2514d24e0'
down_revision = 'e3e87c690f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'end_location')
    op.drop_column('drives', 'icked_up')
    op.drop_column('drives', 'start_location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drives', sa.Column('start_location', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('drives', sa.Column('icked_up', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('drives', sa.Column('end_location', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
