"""empty message

Revision ID: 4b701e7574e5
Revises: 4d39de8cf56b
Create Date: 2017-11-07 14:14:34.635792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b701e7574e5'
down_revision = '4d39de8cf56b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drives', sa.Column('current_lat', sa.String(length=100), nullable=True))
    op.add_column('drives', sa.Column('current_lng', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'current_lng')
    op.drop_column('drives', 'current_lat')
    # ### end Alembic commands ###
