"""empty message

Revision ID: 4d39de8cf56b
Revises: 88fe30871956
Create Date: 2017-11-07 14:14:23.228232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d39de8cf56b'
down_revision = '88fe30871956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'current_lng')
    op.drop_column('drives', 'current_lat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drives', sa.Column('current_lat', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('drives', sa.Column('current_lng', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
