"""empty message

Revision ID: 512be19f8e0e
Revises: 7c3091049221
Create Date: 2017-10-22 21:35:53.059918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '512be19f8e0e'
down_revision = '7c3091049221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drives', 'customer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('drives', 'end_location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('drives', 'start_location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drives', 'start_location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('drives', 'end_location',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('drives', 'customer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
