"""empty message

Revision ID: 6ebadc5a251c
Revises: 512be19f8e0e
Create Date: 2017-10-24 11:16:29.333142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ebadc5a251c'
down_revision = '512be19f8e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drives', sa.Column('picked_up', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'picked_up')
    # ### end Alembic commands ###
