"""empty message

Revision ID: 793b9bc21c7a
Revises: d728ca156173
Create Date: 2017-10-20 23:53:54.606155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '793b9bc21c7a'
down_revision = 'd728ca156173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drives')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drives',
    sa.Column('ride_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('start_location', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('end_location', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('time_finished', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ride_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
