"""empty message

Revision ID: 81500eafc73c
Revises: 15e823d829bd
Create Date: 2017-11-02 07:57:14.170111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81500eafc73c'
down_revision = '15e823d829bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', mysql.VARCHAR(length=50), nullable=True))
    op.create_index('username', 'users', ['username'], unique=True)
    # ### end Alembic commands ###
