"""empty message

Revision ID: 88fe30871956
Revises: c102e28963f6
Create Date: 2017-11-07 11:17:20.721598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fe30871956'
down_revision = 'c102e28963f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drives', sa.Column('current_lat', sa.Integer(), nullable=True))
    op.add_column('drives', sa.Column('current_lng', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'current_lng')
    op.drop_column('drives', 'current_lat')
    # ### end Alembic commands ###
