"""empty message

Revision ID: be9585e29ff2
Revises: d5e8494df211
Create Date: 2017-10-21 10:31:10.669809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be9585e29ff2'
down_revision = 'd5e8494df211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password2', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password2')
    # ### end Alembic commands ###
