"""empty message

Revision ID: c102e28963f6
Revises: 822887c2c395
Create Date: 2017-11-06 10:28:18.600598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c102e28963f6'
down_revision = '822887c2c395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drives',
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('start_location', sa.String(length=100), nullable=False),
    sa.Column('end_location', sa.String(length=100), nullable=False),
    sa.Column('time_finished', sa.String(length=50), nullable=True),
    sa.Column('picked_up', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ride_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drives')
    # ### end Alembic commands ###
