"""empty message

Revision ID: d5e8494df211
Revises: a1974b37803f
Create Date: 2017-10-21 10:27:21.584926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e8494df211'
down_revision = 'a1974b37803f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password1', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password1')
    # ### end Alembic commands ###
