"""empty message

Revision ID: d728ca156173
Revises: 6d2d9ad9e804
Create Date: 2017-10-20 23:53:13.868966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd728ca156173'
down_revision = '6d2d9ad9e804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drives',
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('start_location', sa.String(length=50), nullable=True),
    sa.Column('end_location', sa.String(length=50), nullable=True),
    sa.Column('time_finished', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('ride_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('drives')
    # ### end Alembic commands ###
