"""empty message

Revision ID: d818f02258d6
Revises: be9585e29ff2
Create Date: 2017-10-21 10:32:07.409701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd818f02258d6'
down_revision = 'be9585e29ff2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password2')
    op.drop_column('users', 'password1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password1', mysql.VARCHAR(length=25), nullable=False))
    op.add_column('users', sa.Column('password2', mysql.VARCHAR(length=25), nullable=False))
    # ### end Alembic commands ###
