"""empty message

Revision ID: e3e87c690f9d
Revises: 
Create Date: 2017-11-06 10:25:57.123711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e87c690f9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drives', sa.Column('icked_up', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drives', 'icked_up')
    # ### end Alembic commands ###
